//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajTakipOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liste
    {
        public int ID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
    
        public virtual Öğrenciler Öğrenciler { get; set; }
    }
}
