//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajTakipOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkulAyar
    {
        public int ID { get; set; }
        public string okulAdi { get; set; }
        public string ogretimYili { get; set; }
        public string yariYili { get; set; }
        public Nullable<byte> stajSure { get; set; }
        public Nullable<System.DateTime> baslamaTarihi { get; set; }
        public Nullable<System.DateTime> bitisTarihi { get; set; }
    }
}
