//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajTakipOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programlar()
        {
            this.Öğrenciler = new HashSet<Öğrenciler>();
        }
    
        public int ID { get; set; }
        public string ProgramAdi { get; set; }
        public string ProgramKisaAdi { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<int> DanismaniBir { get; set; }
        public Nullable<int> Danismaniki { get; set; }
    
        public virtual Akademisyen Akademisyen { get; set; }
        public virtual Akademisyen Akademisyen1 { get; set; }
        public virtual Bölümler Bölümler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Öğrenciler> Öğrenciler { get; set; }
    }
}
