//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajTakipOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class YazdırılacakSayfaSayıları
    {
        public int ID { get; set; }
        public Nullable<byte> StajBasvuruFormu { get; set; }
        public Nullable<byte> İsverenBilgiFormu { get; set; }
        public Nullable<byte> SigortalamaYazisi { get; set; }
        public Nullable<byte> BosRaporSayfasi { get; set; }
        public Nullable<byte> DevamTakipCizelgesi { get; set; }
        public Nullable<byte> DegerlendirmeFormu { get; set; }
        public Nullable<byte> Taahhütname { get; set; }
    }
}
