//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajTakipOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Öğrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Öğrenciler()
        {
            this.Liste = new HashSet<Liste>();
        }
    
        public int ID { get; set; }
        public string ogrenciNo { get; set; }
        public string tcKimlikNo { get; set; }
        public string adi { get; set; }
        public string soyAdi { get; set; }
        public string cinsiyet { get; set; }
        public string dogumYeri { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public Nullable<int> programID { get; set; }
        public Nullable<byte> sinifi { get; set; }
        public string telefon { get; set; }
        public string ikametAdresi { get; set; }
        public string ikametAdresİl { get; set; }
        public string ikametAdresİlce { get; set; }
        public string eposta { get; set; }
        public string stajDurumu { get; set; }
        public string stajSonuc { get; set; }
        public string kimlikID { get; set; }
        public string anneAdi { get; set; }
        public string babaAdi { get; set; }
        public string uyrugu { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public string kayitNedeni { get; set; }
        public Nullable<byte> cezaSayisi { get; set; }
        public Nullable<byte> aktifDönemDersKayitSayisi { get; set; }
        public string medeniHali { get; set; }
        public string mahalleKöy { get; set; }
        public Nullable<int> ciltNo { get; set; }
        public Nullable<int> aileSiraNo { get; set; }
        public Nullable<int> siraNo { get; set; }
        public string nüfKayİl { get; set; }
        public string nüfKayİlçe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liste> Liste { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
